version: '2'
services:
    gnp-app:
        image: gnp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gnp-mysql:3306/gnp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gnp-elasticsearch:9300
        ports:
            - 8080:8080
    gnp-mysql:
        extends:
            file: mysql.yml
            service: gnp-mysql
    gnp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gnp-elasticsearch
